//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 09:14:14 ¿ÀÀü KST 
//


package stw.eai.dhl.xml.request;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import stw.eai.dhl.xml.datatypes.*;



/**
 * Root element of shipment validation request
 * 
 * <p>Java class for ShipmentValidateRequestEA element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="ShipmentValidateRequestEA">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="Request" type="{http://www.dhl.com/datatypes_EA}Request"/>
 *           &lt;element name="NewShipper" type="{http://www.dhl.com/datatypes_EA}YesNo" minOccurs="0"/>
 *           &lt;element name="LanguageCode" type="{http://www.dhl.com/datatypes_EA}LanguageCode"/>
 *           &lt;element name="PiecesEnabled" type="{http://www.dhl.com/datatypes_EA}PiecesEnabled" minOccurs="0"/>
 *           &lt;element name="Billing" type="{http://www.dhl.com/datatypes_EA}Billing"/>
 *           &lt;element name="Consignee" type="{http://www.dhl.com/datatypes_EA}Consignee"/>
 *           &lt;element name="Commodity" type="{http://www.dhl.com/datatypes_EA}Commodity" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="Dutiable" type="{http://www.dhl.com/datatypes_EA}Dutiable" minOccurs="0"/>
 *           &lt;element name="ExportDeclaration" type="{http://www.dhl.com/datatypes_EA}ExportDeclaration" minOccurs="0"/>
 *           &lt;element name="Reference" type="{http://www.dhl.com/datatypes_EA}Reference" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="ShipmentDetails" type="{http://www.dhl.com/datatypes_EA}ShipmentDetails"/>
 *           &lt;element name="Shipper" type="{http://www.dhl.com/datatypes_EA}Shipper"/>
 *           &lt;element name="SpecialService" type="{http://www.dhl.com/datatypes_EA}SpecialService" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="Place" type="{http://www.dhl.com/datatypes_EA}Place" minOccurs="0"/>
 *           &lt;element name="EProcShip" type="{http://www.dhl.com/datatypes_EA}YesNo" minOccurs="0"/>
 *           &lt;element name="Airwaybill" type="{http://www.dhl.com/datatypes_EA}AWBNumber" minOccurs="0"/>
 *           &lt;element name="DocImages" type="{http://www.dhl.com/datatypes_EA}DocImages" minOccurs="0"/>
 *           &lt;element name="LabelImageFormat" type="{http://www.dhl.com/datatypes_EA}LabelImageFormat" minOccurs="0"/>
 *           &lt;element name="RequestArchiveDoc" type="{http://www.dhl.com/datatypes_EA}YesNo" minOccurs="0"/>
 *           &lt;element name="Label" type="{http://www.dhl.com/datatypes_EA}Label" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "request",
    "newShipper",
    "languageCode",
    "piecesEnabled",
    "billing",
    "consignee",
    "commodity",
    "dutiable",
    "exportDeclaration",
    "reference",
    "shipmentDetails",
    "shipper",
    "specialService",
    "place",
    "eProcShip",
    "airwaybill",
    "docImages",
    "labelImageFormat",
    "requestArchiveDoc",
    "label"
})
@XmlRootElement(name = "ShipmentValidateRequestEA", namespace = "http://www.dhl.com")
public class ShipmentValidateRequestEA {

    @XmlElement(name = "Request", required = true)
    protected Request request;
    @XmlElement(name = "NewShipper")
    protected YesNo newShipper;
    @XmlElement(name = "LanguageCode", required = true)
    protected String languageCode;
    @XmlElement(name = "PiecesEnabled")
    protected PiecesEnabled piecesEnabled;
    @XmlElement(name = "Billing", required = true)
    protected Billing billing;
    @XmlElement(name = "Consignee", required = true)
    protected Consignee consignee;
    @XmlElement(name = "Commodity", required = true)
    protected List<Commodity> commodity;
    @XmlElement(name = "Dutiable")
    protected Dutiable dutiable;
    @XmlElement(name = "ExportDeclaration")
    protected ExportDeclaration exportDeclaration;
    @XmlElement(name = "Reference", required = true)
    protected List<Reference> reference;
    @XmlElement(name = "ShipmentDetails", required = true)
    protected ShipmentDetails shipmentDetails;
    @XmlElement(name = "Shipper", required = true)
    protected Shipper shipper;
    @XmlElement(name = "SpecialService", required = true)
    protected List<SpecialService> specialService;
    @XmlElement(name = "Place")
    protected Place place;
    @XmlElement(name = "EProcShip")
    protected YesNo eProcShip;
    @XmlElement(name = "Airwaybill")
    protected String airwaybill;
    @XmlElement(name = "DocImages")
    protected DocImages docImages;
    @XmlElement(name = "LabelImageFormat")
    protected LabelImageFormat labelImageFormat;
    @XmlElement(name = "RequestArchiveDoc")
    protected YesNo requestArchiveDoc;
    @XmlElement(name = "Label")
    protected Label label;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link Request }
     *     
     */
    public Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request }
     *     
     */
    public void setRequest(Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the newShipper property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getNewShipper() {
        return newShipper;
    }

    /**
     * Sets the value of the newShipper property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setNewShipper(YesNo value) {
        this.newShipper = value;
    }

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageCode() {
        return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageCode(String value) {
        this.languageCode = value;
    }

    /**
     * Gets the value of the piecesEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link PiecesEnabled }
     *     
     */
    public PiecesEnabled getPiecesEnabled() {
        return piecesEnabled;
    }

    /**
     * Sets the value of the piecesEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link PiecesEnabled }
     *     
     */
    public void setPiecesEnabled(PiecesEnabled value) {
        this.piecesEnabled = value;
    }

    /**
     * Gets the value of the billing property.
     * 
     * @return
     *     possible object is
     *     {@link Billing }
     *     
     */
    public Billing getBilling() {
        return billing;
    }

    /**
     * Sets the value of the billing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Billing }
     *     
     */
    public void setBilling(Billing value) {
        this.billing = value;
    }

    /**
     * Gets the value of the consignee property.
     * 
     * @return
     *     possible object is
     *     {@link Consignee }
     *     
     */
    public Consignee getConsignee() {
        return consignee;
    }

    /**
     * Sets the value of the consignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Consignee }
     *     
     */
    public void setConsignee(Consignee value) {
        this.consignee = value;
    }

    /**
     * Gets the value of the commodity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commodity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommodity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Commodity }
     * 
     * 
     */
    public List<Commodity> getCommodity() {
        if (commodity == null) {
            commodity = new ArrayList<Commodity>();
        }
        return this.commodity;
    }

    /**
     * Gets the value of the dutiable property.
     * 
     * @return
     *     possible object is
     *     {@link Dutiable }
     *     
     */
    public Dutiable getDutiable() {
        return dutiable;
    }

    /**
     * Sets the value of the dutiable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dutiable }
     *     
     */
    public void setDutiable(Dutiable value) {
        this.dutiable = value;
    }

    /**
     * Gets the value of the exportDeclaration property.
     * 
     * @return
     *     possible object is
     *     {@link ExportDeclaration }
     *     
     */
    public ExportDeclaration getExportDeclaration() {
        return exportDeclaration;
    }

    /**
     * Sets the value of the exportDeclaration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExportDeclaration }
     *     
     */
    public void setExportDeclaration(ExportDeclaration value) {
        this.exportDeclaration = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getReference() {
        if (reference == null) {
            reference = new ArrayList<Reference>();
        }
        return this.reference;
    }

    /**
     * Gets the value of the shipmentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentDetails }
     *     
     */
    public ShipmentDetails getShipmentDetails() {
        return shipmentDetails;
    }

    /**
     * Sets the value of the shipmentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentDetails }
     *     
     */
    public void setShipmentDetails(ShipmentDetails value) {
        this.shipmentDetails = value;
    }

    /**
     * Gets the value of the shipper property.
     * 
     * @return
     *     possible object is
     *     {@link Shipper }
     *     
     */
    public Shipper getShipper() {
        return shipper;
    }

    /**
     * Sets the value of the shipper property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shipper }
     *     
     */
    public void setShipper(Shipper value) {
        this.shipper = value;
    }

    /**
     * Gets the value of the specialService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpecialService }
     * 
     * 
     */
    public List<SpecialService> getSpecialService() {
        if (specialService == null) {
            specialService = new ArrayList<SpecialService>();
        }
        return this.specialService;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link Place }
     *     
     */
    public Place getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link Place }
     *     
     */
    public void setPlace(Place value) {
        this.place = value;
    }

    /**
     * Gets the value of the eProcShip property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getEProcShip() {
        return eProcShip;
    }

    /**
     * Sets the value of the eProcShip property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setEProcShip(YesNo value) {
        this.eProcShip = value;
    }

    /**
     * Gets the value of the airwaybill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirwaybill() {
        return airwaybill;
    }

    /**
     * Sets the value of the airwaybill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirwaybill(String value) {
        this.airwaybill = value;
    }

    /**
     * Gets the value of the docImages property.
     * 
     * @return
     *     possible object is
     *     {@link DocImages }
     *     
     */
    public DocImages getDocImages() {
        return docImages;
    }

    /**
     * Sets the value of the docImages property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocImages }
     *     
     */
    public void setDocImages(DocImages value) {
        this.docImages = value;
    }

    /**
     * Gets the value of the labelImageFormat property.
     * 
     * @return
     *     possible object is
     *     {@link LabelImageFormat }
     *     
     */
    public LabelImageFormat getLabelImageFormat() {
        return labelImageFormat;
    }

    /**
     * Sets the value of the labelImageFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelImageFormat }
     *     
     */
    public void setLabelImageFormat(LabelImageFormat value) {
        this.labelImageFormat = value;
    }

    /**
     * Gets the value of the requestArchiveDoc property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getRequestArchiveDoc() {
        return requestArchiveDoc;
    }

    /**
     * Sets the value of the requestArchiveDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setRequestArchiveDoc(YesNo value) {
        this.requestArchiveDoc = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link Label }
     *     
     */
    public Label getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link Label }
     *     
     */
    public void setLabel(Label value) {
        this.label = value;
    }

}
