//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.12 at 09:14:14 ¿ÀÀü KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dhl.com/datatypes_EA")
package stw.eai.dhl.xml.datatypes;
